"""
NMEA 0183 API
"""
from __future__ import annotations
import collections.abc
import datetime
import nmealib._core
import typing
__all__: list[str] = ['APB', 'DBT', 'DPT', 'GGA', 'GLL', 'GSA', 'GSV', 'GSVSatelliteInfo', 'HDG', 'HDM', 'MTW', 'MWV', 'Message0183', 'Nmea0183Factory', 'RMA', 'RMB', 'RMC', 'VHW', 'VLW', 'VTG', 'VWR', 'XDR', 'XDRTransducerMeasurement', 'XTE', 'ZDA']
class APB(Message0183):
    def __init__(self, talker_id: str, status1: str, status2: str, cross_track_error_magnitude: typing.SupportsFloat | typing.SupportsIndex, direction_to_steer: str, cross_track_units: str, arrival_circle_status: str, perpendicular_passed_at_waypoint: str, bearing_origin_to_destination: typing.SupportsFloat | typing.SupportsIndex, bearing_origin_to_destination_type: str, destination_waypoint_id: str, bearing_present_to_destination: typing.SupportsFloat | typing.SupportsIndex, bearing_present_to_destination_type: str, heading_to_steer_to_destination_waypoint: typing.SupportsFloat | typing.SupportsIndex, heading_to_steer_to_destination_waypoint_type: str) -> None:
        ...
    def get_arrival_circle_status(self) -> str:
        ...
    def get_bearing_origin_to_destination(self) -> float:
        ...
    def get_bearing_origin_to_destination_type(self) -> str:
        ...
    def get_bearing_present_to_destination(self) -> float:
        ...
    def get_bearing_present_to_destination_type(self) -> str:
        ...
    def get_cross_track_error_magnitude(self) -> float:
        ...
    def get_cross_track_units(self) -> str:
        ...
    def get_destination_waypoint_id(self) -> str:
        ...
    def get_direction_to_steer(self) -> str:
        ...
    def get_heading_to_steer_to_destination_waypoint(self) -> float:
        ...
    def get_heading_to_steer_to_destination_waypoint_type(self) -> str:
        ...
    def get_perpendicular_passed_at_waypoint(self) -> str:
        ...
    def get_status1(self) -> str:
        ...
    def get_status2(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
class DBT(Message0183):
    def __init__(self, talker_id: str, depth_feet: typing.SupportsFloat | typing.SupportsIndex, feet_unit: str, depth_meters: typing.SupportsFloat | typing.SupportsIndex, meters_unit: str, depth_fathoms: typing.SupportsFloat | typing.SupportsIndex, fathoms_unit: str) -> None:
        ...
    def get_depth_fathoms(self) -> float:
        ...
    def get_depth_feet(self) -> float:
        ...
    def get_depth_meters(self) -> float:
        ...
    def get_fathoms_unit(self) -> str:
        ...
    def get_feet_unit(self) -> str:
        ...
    def get_meters_unit(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
class DPT(Message0183):
    def __init__(self, talker_id: str, water_depth_meters: typing.SupportsFloat | typing.SupportsIndex, transducer_offset: typing.SupportsFloat | typing.SupportsIndex, max_range_scale: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def get_max_range_scale(self) -> float:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_transducer_offset(self) -> float:
        ...
    def get_water_depth_meters(self) -> float:
        ...
class GGA(Message0183):
    def __init__(self, talker_id: str, utc_time: typing.SupportsFloat | typing.SupportsIndex, latitude: typing.SupportsFloat | typing.SupportsIndex, latitude_direction: str, longitude: typing.SupportsFloat | typing.SupportsIndex, longitude_direction: str, gps_quality: typing.SupportsInt | typing.SupportsIndex, satellites: typing.SupportsInt | typing.SupportsIndex, hdop: typing.SupportsFloat | typing.SupportsIndex, altitude: typing.SupportsFloat | typing.SupportsIndex, altitude_units: str, geoidal_separation: typing.SupportsFloat | typing.SupportsIndex, geoidal_separation_units: str, dgps_age: typing.SupportsFloat | typing.SupportsIndex, dgps_reference_station_id: str) -> None:
        ...
    def get_altitude(self) -> float:
        ...
    def get_altitude_units(self) -> str:
        ...
    def get_dgps_age(self) -> float:
        ...
    def get_dgps_reference_station_id(self) -> str:
        ...
    def get_geoidal_separation(self) -> float:
        ...
    def get_geoidal_separation_units(self) -> str:
        ...
    def get_gps_quality(self) -> int:
        ...
    def get_hdop(self) -> float:
        ...
    def get_latitude(self) -> float:
        ...
    def get_latitude_direction(self) -> str:
        ...
    def get_longitude(self) -> float:
        ...
    def get_longitude_direction(self) -> str:
        ...
    def get_satellites(self) -> int:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_utc_time(self) -> float:
        ...
class GLL(Message0183):
    def __init__(self, talker_id: str, latitude: typing.SupportsFloat | typing.SupportsIndex, latitude_direction: str, longitude: typing.SupportsFloat | typing.SupportsIndex, longitude_direction: str, utc_time: typing.SupportsFloat | typing.SupportsIndex, status: str, mode_indicator: str) -> None:
        ...
    def get_latitude(self) -> float:
        ...
    def get_latitude_direction(self) -> str:
        ...
    def get_longitude(self) -> float:
        ...
    def get_longitude_direction(self) -> str:
        ...
    def get_mode_indicator(self) -> str:
        ...
    def get_status(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_utc_time(self) -> float:
        ...
class GSA(Message0183):
    def __init__(self, talker_id: str, selection_mode: str, mode: typing.SupportsInt | typing.SupportsIndex, satellite_ids: typing.Annotated[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], "FixedSize(12)"], pdop: typing.SupportsFloat | typing.SupportsIndex, hdop: typing.SupportsFloat | typing.SupportsIndex, vdop: typing.SupportsFloat | typing.SupportsIndex, system_id: typing.SupportsInt | typing.SupportsIndex | None = None) -> None:
        ...
    def get_hdop(self) -> float:
        ...
    def get_mode(self) -> int:
        ...
    def get_pdop(self) -> float:
        ...
    def get_satellite_id(self, index: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def get_satellite_ids(self) -> typing.Annotated[list[int], "FixedSize(12)"]:
        ...
    def get_selection_mode(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_system_id(self) -> int | None:
        ...
    def get_vdop(self) -> float:
        ...
    def has_system_id(self) -> bool:
        ...
class GSV(Message0183):
    def __init__(self, talker_id: str, total_sentences: typing.SupportsInt | typing.SupportsIndex, sentence_number: typing.SupportsInt | typing.SupportsIndex, satellites_in_view: typing.SupportsInt | typing.SupportsIndex, satellites: collections.abc.Sequence[GSVSatelliteInfo], signal_id: typing.SupportsInt | typing.SupportsIndex | None = None) -> None:
        ...
    def get_satellite_count(self) -> int:
        ...
    def get_satellites(self) -> list[GSVSatelliteInfo]:
        ...
    def get_satellites_in_view(self) -> int:
        ...
    def get_sentence_number(self) -> int:
        ...
    def get_signal_id(self) -> int | None:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_total_sentences(self) -> int:
        ...
    def has_signal_id(self) -> bool:
        ...
class GSVSatelliteInfo:
    def __init__(self) -> None:
        ...
    @property
    def azimuth(self) -> int:
        ...
    @azimuth.setter
    def azimuth(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def elevation(self) -> int:
        ...
    @elevation.setter
    def elevation(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def satellite_id(self) -> int:
        ...
    @satellite_id.setter
    def satellite_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def snr(self) -> int | None:
        ...
    @snr.setter
    def snr(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
class HDG(Message0183):
    def __init__(self, talker_id: str, magnetic_heading: typing.SupportsFloat | typing.SupportsIndex, magnetic_deviation: typing.SupportsFloat | typing.SupportsIndex, deviation_direction: str, magnetic_variation: typing.SupportsFloat | typing.SupportsIndex, variation_direction: str) -> None:
        ...
    def get_deviation_direction(self) -> str:
        ...
    def get_magnetic_deviation(self) -> float:
        ...
    def get_magnetic_heading(self) -> float:
        ...
    def get_magnetic_variation(self) -> float:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_variation_direction(self) -> str:
        ...
class HDM(Message0183):
    def __init__(self, talker_id: str, heading: typing.SupportsFloat | typing.SupportsIndex, indicator: str) -> None:
        ...
    def get_heading(self) -> float:
        ...
    def get_indicator(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
class MTW(Message0183):
    def __init__(self, talker_id: str, temperature: typing.SupportsFloat | typing.SupportsIndex, unit: str) -> None:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_temperature(self) -> float:
        ...
    def get_unit(self) -> str:
        ...
class MWV(Message0183):
    def __init__(self, talker_id: str, wind_angle: typing.SupportsFloat | typing.SupportsIndex, reference: str, wind_speed: typing.SupportsFloat | typing.SupportsIndex, wind_speed_units: str, status: str) -> None:
        ...
    def get_reference(self) -> str:
        ...
    def get_status(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_wind_angle(self) -> float:
        ...
    def get_wind_speed(self) -> float:
        ...
    def get_wind_speed_units(self) -> str:
        ...
class Message0183(nmealib._core.Message):
    @staticmethod
    def convert_nmea_coordinate_to_decimal_degrees(nmea_coordinate: str) -> float:
        ...
    def get_calculated_checksum_str(self) -> str:
        ...
    def get_checksum_str(self) -> str:
        ...
    def get_payload(self) -> str:
        ...
    def get_sentence_type(self) -> str:
        ...
    def get_start_char(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_talker(self) -> str:
        ...
class Nmea0183Factory:
    @staticmethod
    def create(raw: str, timestamp: datetime.datetime = ...) -> Message0183:
        ...
class RMA(Message0183):
    def __init__(self, talker_id: str, status: str, latitude: typing.SupportsFloat | typing.SupportsIndex, latitude_direction: str, longitude: typing.SupportsFloat | typing.SupportsIndex, longitude_direction: str, time_difference_a: typing.SupportsFloat | typing.SupportsIndex, time_difference_b: typing.SupportsFloat | typing.SupportsIndex, speed_over_ground: typing.SupportsFloat | typing.SupportsIndex, track_made_good: typing.SupportsFloat | typing.SupportsIndex, magnetic_variation: typing.SupportsFloat | typing.SupportsIndex, variation_direction: str) -> None:
        ...
    def get_latitude(self) -> float:
        ...
    def get_latitude_direction(self) -> str:
        ...
    def get_longitude(self) -> float:
        ...
    def get_longitude_direction(self) -> str:
        ...
    def get_magnetic_variation(self) -> float:
        ...
    def get_speed_over_ground(self) -> float:
        ...
    def get_status(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_time_difference_a(self) -> float:
        ...
    def get_time_difference_b(self) -> float:
        ...
    def get_track_made_good(self) -> float:
        ...
    def get_variation_direction(self) -> str:
        ...
class RMB(Message0183):
    def __init__(self, talker_id: str, status: str, cross_track_error_nm: typing.SupportsFloat | typing.SupportsIndex, direction_to_steer: str, origin_waypoint_id: str, destination_waypoint_id: str, destination_latitude: typing.SupportsFloat | typing.SupportsIndex, destination_latitude_hemisphere: str, destination_longitude: typing.SupportsFloat | typing.SupportsIndex, destination_longitude_hemisphere: str, range_to_destination_nm: typing.SupportsFloat | typing.SupportsIndex, bearing_to_destination_true: typing.SupportsFloat | typing.SupportsIndex, destination_closing_velocity_knots: typing.SupportsFloat | typing.SupportsIndex, arrival_status: str, faa_mode_indicator: str | None = None) -> None:
        ...
    def get_arrival_status(self) -> str:
        ...
    def get_bearing_to_destination_true(self) -> float:
        ...
    def get_cross_track_error_nm(self) -> float:
        ...
    def get_destination_closing_velocity_knots(self) -> float:
        ...
    def get_destination_latitude(self) -> float:
        ...
    def get_destination_latitude_hemisphere(self) -> str:
        ...
    def get_destination_longitude(self) -> float:
        ...
    def get_destination_longitude_hemisphere(self) -> str:
        ...
    def get_destination_waypoint_id(self) -> str:
        ...
    def get_direction_to_steer(self) -> str:
        ...
    def get_faa_mode_indicator(self) -> str | None:
        ...
    def get_origin_waypoint_id(self) -> str:
        ...
    def get_range_to_destination_nm(self) -> float:
        ...
    def get_status(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def has_faa_mode_indicator(self) -> bool:
        ...
class RMC(Message0183):
    def __init__(self, talker_id: str, utc_fix: typing.SupportsInt | typing.SupportsIndex, status: str, latitude: typing.SupportsFloat | typing.SupportsIndex, latitude_direction: str, longitude: typing.SupportsFloat | typing.SupportsIndex, longitude_direction: str, speed_over_ground: typing.SupportsFloat | typing.SupportsIndex, course_over_ground: typing.SupportsFloat | typing.SupportsIndex, date: typing.SupportsInt | typing.SupportsIndex, magnetic_variation: typing.SupportsFloat | typing.SupportsIndex, magnetic_variation_direction: str, mode_indicator: str, navigation_status: str) -> None:
        ...
    def get_course_over_ground(self) -> float:
        ...
    def get_date(self) -> int:
        ...
    def get_latitude(self) -> float:
        ...
    def get_latitude_direction(self) -> str:
        ...
    def get_longitude(self) -> float:
        ...
    def get_longitude_direction(self) -> str:
        ...
    def get_magnetic_variation(self) -> float:
        ...
    def get_magnetic_variation_direction(self) -> str:
        ...
    def get_mode_indicator(self) -> str:
        ...
    def get_navigation_status(self) -> str:
        ...
    def get_speed_over_ground(self) -> float:
        ...
    def get_status(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_utc_fix(self) -> int:
        ...
class VHW(Message0183):
    def __init__(self, talker_id: str, heading_true: typing.SupportsFloat | typing.SupportsIndex, heading_magnetic: typing.SupportsFloat | typing.SupportsIndex, speed_knots: typing.SupportsFloat | typing.SupportsIndex, speed_kph: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def get_heading_magnetic(self) -> float:
        ...
    def get_heading_magnetic_type(self) -> str:
        ...
    def get_heading_true(self) -> float:
        ...
    def get_heading_true_type(self) -> str:
        ...
    def get_speed_knots(self) -> float:
        ...
    def get_speed_knots_type(self) -> str:
        ...
    def get_speed_kph(self) -> float:
        ...
    def get_speed_kph_type(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
class VLW(Message0183):
    def __init__(self, talker_id: str, total_water_distance_nm: typing.SupportsFloat | typing.SupportsIndex, water_distance_since_reset_nm: typing.SupportsFloat | typing.SupportsIndex, total_ground_distance_nm: typing.SupportsFloat | typing.SupportsIndex | None = None, ground_distance_since_reset_nm: typing.SupportsFloat | typing.SupportsIndex | None = None) -> None:
        ...
    def get_ground_distance_since_reset_nm(self) -> float:
        ...
    def get_ground_distance_since_reset_unit(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_total_ground_distance_nm(self) -> float:
        ...
    def get_total_ground_distance_unit(self) -> str:
        ...
    def get_total_water_distance_nm(self) -> float:
        ...
    def get_total_water_distance_unit(self) -> str:
        ...
    def get_water_distance_since_reset_nm(self) -> float:
        ...
    def get_water_distance_since_reset_unit(self) -> str:
        ...
    def has_ground_distance_data(self) -> bool:
        ...
class VTG(Message0183):
    def __init__(self, talker_id: str, course_over_ground_true: typing.SupportsFloat | typing.SupportsIndex, course_over_ground_magnetic: typing.SupportsFloat | typing.SupportsIndex, speed_over_ground_knots: typing.SupportsFloat | typing.SupportsIndex, speed_over_ground_kph: typing.SupportsFloat | typing.SupportsIndex, faa_mode_indicator: str | None = None, legacy_format: bool = False) -> None:
        ...
    def get_course_over_ground_magnetic(self) -> float:
        ...
    def get_course_over_ground_magnetic_type(self) -> str:
        ...
    def get_course_over_ground_true(self) -> float:
        ...
    def get_course_over_ground_true_type(self) -> str:
        ...
    def get_faa_mode_indicator(self) -> str | None:
        ...
    def get_speed_over_ground_knots(self) -> float:
        ...
    def get_speed_over_ground_knots_type(self) -> str:
        ...
    def get_speed_over_ground_kph(self) -> float:
        ...
    def get_speed_over_ground_kph_type(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def has_faa_mode_indicator(self) -> bool:
        ...
    def is_legacy_format(self) -> bool:
        ...
class VWR(Message0183):
    def __init__(self, talker_id: str, wind_angle: typing.SupportsFloat | typing.SupportsIndex, wind_side: str, speed_knots: typing.SupportsFloat | typing.SupportsIndex, speed_mps: typing.SupportsFloat | typing.SupportsIndex, speed_kph: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def get_speed_knots(self) -> float:
        ...
    def get_speed_knots_unit(self) -> str:
        ...
    def get_speed_kph(self) -> float:
        ...
    def get_speed_kph_unit(self) -> str:
        ...
    def get_speed_mps(self) -> float:
        ...
    def get_speed_mps_unit(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_wind_angle(self) -> float:
        ...
    def get_wind_side(self) -> str:
        ...
class XDR(Message0183):
    def __init__(self, talker_id: str, transducers: collections.abc.Sequence[XDRTransducerMeasurement]) -> None:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_transducer_count(self) -> int:
        ...
    def get_transducers(self) -> list[XDRTransducerMeasurement]:
        ...
class XDRTransducerMeasurement:
    name: str
    transducer_type: str
    units: str
    def __init__(self) -> None:
        ...
    @property
    def measurement(self) -> float:
        ...
    @measurement.setter
    def measurement(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class XTE(Message0183):
    def __init__(self, talker_id: str, status1: str, status2: str, cross_track_error: typing.SupportsFloat | typing.SupportsIndex, steer_direction: str, cross_track_units: str, faa_mode_indicator: str | None = None) -> None:
        ...
    def get_cross_track_error(self) -> float:
        ...
    def get_cross_track_units(self) -> str:
        ...
    def get_faa_mode_indicator(self) -> str | None:
        ...
    def get_status1(self) -> str:
        ...
    def get_status2(self) -> str:
        ...
    def get_steer_direction(self) -> str:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def has_faa_mode_indicator(self) -> bool:
        ...
class ZDA(Message0183):
    def __init__(self, talker_id: str, utc_time: typing.SupportsFloat | typing.SupportsIndex, day: typing.SupportsInt | typing.SupportsIndex, month: typing.SupportsInt | typing.SupportsIndex, year: typing.SupportsInt | typing.SupportsIndex, local_zone_hours: typing.SupportsInt | typing.SupportsIndex, local_zone_minutes: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def get_day(self) -> int:
        ...
    def get_local_zone_hours(self) -> int:
        ...
    def get_local_zone_minutes(self) -> int:
        ...
    def get_month(self) -> int:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_utc_time(self) -> float:
        ...
    def get_year(self) -> int:
        ...
