"""
NMEA 2000 API
"""
from __future__ import annotations
import datetime
import nmealib._core
import typing
__all__: list[str] = ['Angle', 'AngularRate', 'Byte', 'HalfByte', 'Latitude', 'Longitude', 'Message2000', 'Nmea2000Factory', 'PGN127245', 'PGN127250', 'PGN127251', 'PGN127257', 'PGN128259', 'PGN129025', 'PGN129026', 'PGN130306', 'SignedAngle', 'Speed']
class Angle:
    @staticmethod
    def from_raw(raw: typing.SupportsInt | typing.SupportsIndex) -> Angle:
        ...
    @staticmethod
    def from_value(value: typing.SupportsFloat | typing.SupportsIndex) -> Angle:
        ...
    def __repr__(self) -> str:
        ...
    def get_raw(self) -> int:
        ...
    def get_value(self) -> float:
        ...
    def is_valid(self) -> bool:
        ...
    def to_string(self) -> str:
        ...
class AngularRate:
    @staticmethod
    def from_raw(raw: typing.SupportsInt | typing.SupportsIndex) -> AngularRate:
        ...
    @staticmethod
    def from_value(value: typing.SupportsFloat | typing.SupportsIndex) -> AngularRate:
        ...
    def __repr__(self) -> str:
        ...
    def get_raw(self) -> int:
        ...
    def get_value(self) -> float:
        ...
    def is_valid(self) -> bool:
        ...
    def to_string(self) -> str:
        ...
class Byte:
    @staticmethod
    def from_raw(raw: typing.SupportsInt | typing.SupportsIndex) -> Byte:
        ...
    @staticmethod
    def from_value(value: typing.SupportsInt | typing.SupportsIndex) -> Byte:
        ...
    def __repr__(self) -> str:
        ...
    def get_raw(self) -> int:
        ...
    def get_value(self) -> int:
        ...
    def is_valid(self) -> bool:
        ...
    def to_string(self) -> str:
        ...
class HalfByte:
    @staticmethod
    def from_raw(raw: typing.SupportsInt | typing.SupportsIndex) -> HalfByte:
        ...
    @staticmethod
    def from_value(value: typing.SupportsInt | typing.SupportsIndex) -> HalfByte:
        ...
    def __repr__(self) -> str:
        ...
    def get_raw(self) -> int:
        ...
    def get_value(self) -> int:
        ...
    def is_valid(self) -> bool:
        ...
    def to_string(self) -> str:
        ...
class Latitude:
    @staticmethod
    def from_raw(raw: typing.SupportsInt | typing.SupportsIndex) -> Latitude:
        ...
    @staticmethod
    def from_value(value: typing.SupportsFloat | typing.SupportsIndex) -> Latitude:
        ...
    def __repr__(self) -> str:
        ...
    def get_raw(self) -> int:
        ...
    def get_value(self) -> float:
        ...
    def is_valid(self) -> bool:
        ...
    def to_string(self) -> str:
        ...
class Longitude:
    @staticmethod
    def from_raw(raw: typing.SupportsInt | typing.SupportsIndex) -> Longitude:
        ...
    @staticmethod
    def from_value(value: typing.SupportsFloat | typing.SupportsIndex) -> Longitude:
        ...
    def __repr__(self) -> str:
        ...
    def get_raw(self) -> int:
        ...
    def get_value(self) -> float:
        ...
    def is_valid(self) -> bool:
        ...
    def to_string(self) -> str:
        ...
class Message2000(nmealib._core.Message):
    def get_can_frame(self) -> list[int]:
        ...
    def get_can_frame_length(self) -> int:
        ...
    def get_can_id(self) -> list[int]:
        ...
    def get_data_page(self) -> bool:
        ...
    def get_destination_address(self) -> int:
        ...
    def get_pdu_format(self) -> int:
        ...
    def get_pdu_specific(self) -> int:
        ...
    def get_pgn(self) -> int:
        ...
    def get_priority(self) -> int:
        ...
    def get_reserved(self) -> bool:
        ...
    def get_source_address(self) -> int:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
class Nmea2000Factory:
    @staticmethod
    def create(raw: str, timestamp: datetime.datetime = ...) -> Message2000:
        ...
class PGN127245(Message2000):
    @typing.overload
    def __init__(self, rudder_id: typing.SupportsInt | typing.SupportsIndex, direction: HalfByte, angle_order: SignedAngle, position: SignedAngle) -> None:
        ...
    @typing.overload
    def __init__(self, rudder_id: typing.SupportsInt | typing.SupportsIndex, direction: typing.SupportsInt | typing.SupportsIndex, angle_order_radians: typing.SupportsFloat | typing.SupportsIndex, position_radians: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def get_angle_order(self) -> SignedAngle:
        ...
    def get_angle_order_degrees(self) -> float:
        ...
    def get_direction(self) -> HalfByte:
        ...
    def get_direction_string(self) -> str:
        ...
    def get_position(self) -> SignedAngle:
        ...
    def get_position_degrees(self) -> float:
        ...
    def get_rudder_id(self) -> int:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
class PGN127250(Message2000):
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, heading: Angle, deviation: SignedAngle, variation: SignedAngle, heading_reference: HalfByte, reserved: Byte) -> None:
        ...
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, heading_radians: typing.SupportsFloat | typing.SupportsIndex, deviation_radians: typing.SupportsFloat | typing.SupportsIndex, variation_radians: typing.SupportsFloat | typing.SupportsIndex, heading_reference: typing.SupportsInt | typing.SupportsIndex, reserved: typing.SupportsInt | typing.SupportsIndex = 0) -> None:
        ...
    def get_deviation(self) -> SignedAngle:
        ...
    def get_deviation_degrees(self) -> float:
        ...
    def get_heading(self) -> Angle:
        ...
    def get_heading_degrees(self) -> float:
        ...
    def get_heading_reference(self) -> HalfByte:
        ...
    def get_sequence_id(self) -> int:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_variation(self) -> SignedAngle:
        ...
    def get_variation_degrees(self) -> float:
        ...
class PGN127251(Message2000):
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, rate: AngularRate, reserved1: Byte, reserved2: Byte, reserved3: Byte) -> None:
        ...
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, rate_radians_per_second: typing.SupportsFloat | typing.SupportsIndex, reserved1: typing.SupportsInt | typing.SupportsIndex = 0, reserved2: typing.SupportsInt | typing.SupportsIndex = 0, reserved3: typing.SupportsInt | typing.SupportsIndex = 0) -> None:
        ...
    def get_rate(self) -> AngularRate:
        ...
    def get_reserved1(self) -> Byte:
        ...
    def get_reserved2(self) -> Byte:
        ...
    def get_reserved3(self) -> Byte:
        ...
    def get_sequence_id(self) -> int:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
class PGN127257(Message2000):
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, yaw: SignedAngle, pitch: SignedAngle, roll: SignedAngle, reserved: Byte) -> None:
        ...
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, yaw_radians: typing.SupportsFloat | typing.SupportsIndex, pitch_radians: typing.SupportsFloat | typing.SupportsIndex, roll_radians: typing.SupportsFloat | typing.SupportsIndex, reserved: typing.SupportsInt | typing.SupportsIndex = 0) -> None:
        ...
    def get_pitch(self) -> SignedAngle:
        ...
    def get_pitch_degrees(self) -> float:
        ...
    def get_reserved(self) -> Byte:
        ...
    def get_roll(self) -> SignedAngle:
        ...
    def get_roll_degrees(self) -> float:
        ...
    def get_sequence_id(self) -> int:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_yaw(self) -> SignedAngle:
        ...
    def get_yaw_degrees(self) -> float:
        ...
class PGN128259(Message2000):
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, speed_water_referenced: Speed, speed_ground_referenced: Speed, speed_water_referenced_type: Byte, speed_direction: HalfByte, reserved1: Byte, reserved2: HalfByte) -> None:
        ...
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, speed_water_referenced_mps: typing.SupportsFloat | typing.SupportsIndex, speed_ground_referenced_mps: typing.SupportsFloat | typing.SupportsIndex, speed_water_referenced_type: typing.SupportsInt | typing.SupportsIndex, speed_direction: typing.SupportsInt | typing.SupportsIndex, reserved1: typing.SupportsInt | typing.SupportsIndex = 0, reserved2: typing.SupportsInt | typing.SupportsIndex = 0) -> None:
        ...
    def get_reserved1(self) -> Byte:
        ...
    def get_reserved2(self) -> HalfByte:
        ...
    def get_sequence_id(self) -> int:
        ...
    def get_speed_direction(self) -> HalfByte:
        ...
    def get_speed_ground_referenced(self) -> Speed:
        ...
    def get_speed_water_referenced(self) -> Speed:
        ...
    def get_speed_water_referenced_type(self) -> Byte:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
class PGN129025(Message2000):
    @typing.overload
    def __init__(self, latitude: Latitude, longitude: Longitude) -> None:
        ...
    @typing.overload
    def __init__(self, latitude_degrees: typing.SupportsFloat | typing.SupportsIndex, longitude_degrees: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def get_latitude(self) -> Latitude:
        ...
    def get_longitude(self) -> Longitude:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
class PGN129026(Message2000):
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, cog_reference: HalfByte, cog: Angle, sog: Speed) -> None:
        ...
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, cog_reference: HalfByte, reserved1: Byte, cog: Angle, sog: Speed, reserved2: Byte, reserved3: Byte) -> None:
        ...
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, cog_reference: typing.SupportsInt | typing.SupportsIndex, cog_radians: typing.SupportsFloat | typing.SupportsIndex, sog_mps: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def get_cog(self) -> Angle:
        ...
    def get_cog_degrees(self) -> float:
        ...
    def get_cog_reference(self) -> HalfByte:
        ...
    def get_reserved1(self) -> Byte:
        ...
    def get_reserved2(self) -> Byte:
        ...
    def get_reserved3(self) -> Byte:
        ...
    def get_sequence_id(self) -> int:
        ...
    def get_sog(self) -> Speed:
        ...
    def get_sog_knots(self) -> float:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
class PGN130306(Message2000):
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, wind_speed: Speed, wind_direction: Angle, wind_reference: HalfByte) -> None:
        ...
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, wind_speed: Speed, wind_direction: Angle, wind_reference: HalfByte, reserved1: HalfByte, reserved2: Byte, reserved3: Byte) -> None:
        ...
    @typing.overload
    def __init__(self, sequence_id: typing.SupportsInt | typing.SupportsIndex, wind_speed_mps: typing.SupportsFloat | typing.SupportsIndex, wind_direction_radians: typing.SupportsFloat | typing.SupportsIndex, wind_reference: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def get_reserved1(self) -> HalfByte:
        ...
    def get_reserved2(self) -> Byte:
        ...
    def get_reserved3(self) -> Byte:
        ...
    def get_sequence_id(self) -> int:
        ...
    def get_string_content(self, verbose: bool = False) -> str:
        ...
    def get_wind_direction(self) -> Angle:
        ...
    def get_wind_direction_degrees(self) -> float:
        ...
    def get_wind_reference(self) -> HalfByte:
        ...
    def get_wind_speed(self) -> Speed:
        ...
    def get_wind_speed_knots(self) -> float:
        ...
class SignedAngle:
    @staticmethod
    def from_raw(raw: typing.SupportsInt | typing.SupportsIndex) -> SignedAngle:
        ...
    @staticmethod
    def from_value(value: typing.SupportsFloat | typing.SupportsIndex) -> SignedAngle:
        ...
    def __repr__(self) -> str:
        ...
    def get_raw(self) -> int:
        ...
    def get_value(self) -> float:
        ...
    def is_valid(self) -> bool:
        ...
    def to_string(self) -> str:
        ...
class Speed:
    @staticmethod
    def from_raw(raw: typing.SupportsInt | typing.SupportsIndex) -> Speed:
        ...
    @staticmethod
    def from_value(value: typing.SupportsFloat | typing.SupportsIndex) -> Speed:
        ...
    def __repr__(self) -> str:
        ...
    def get_raw(self) -> int:
        ...
    def get_value(self) -> float:
        ...
    def is_valid(self) -> bool:
        ...
    def to_string(self) -> str:
        ...
