name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_CLI=ON
        -S ${{ github.workspace }}

    - name: Build release
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Package library release
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        cmake --install . --component library --prefix nmealib-lib
        tar -czf nmealib-lib.tar.gz nmealib-lib/

    - name: Package cli release
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        cmake --install . --component library --prefix nmealib-cli
        cmake --install . --component cli --prefix nmealib-cli
        tar -czf nmealib-cli.tar.gz nmealib-cli/

    - name: Upload library artifact
      uses: actions/upload-artifact@v4
      with:
        name: nmealib-lib
        path: ${{ steps.strings.outputs.build-output-dir }}/nmealib-lib.tar.gz

    - name: Upload cli artifact
      uses: actions/upload-artifact@v4
      with:
        name: nmealib-cli
        path: ${{ steps.strings.outputs.build-output-dir }}/nmealib-cli.tar.gz

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ steps.strings.outputs.build-output-dir }}/nmealib-lib.tar.gz
          ${{ steps.strings.outputs.build-output-dir }}/nmealib-cli.tar.gz
