name: Run Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B build
        -S .
        -DCMAKE_BUILD_TYPE=Release
        -DENABLE_TESTS=ON
        -DBUILD_TESTING=ON

    - name: Build
      run: cmake --build build --config Release

    - name: Run all tests
      working-directory: build
      run: ctest --output-on-failure --no-tests=error
